// GENERATED by scripts/gen-orb-spec.mjs from docs/orbs/orbs-spec.json (thinking-orbs@0.3.1, specVersion 1.0.0). DO NOT hand-edit — regenerate.
package com.grapsee.gsai.ui.orbs

/**
 * The nine activity states an AI assistant can be in — the logical model the
 * product maps its REAL application states onto (never the reverse; see
 * OrbStateMapping.kt for the honest app-state → orb-state layer).
 */
enum class OrbState(val label: String, val mode: OrbMode) {
    WORKING("Working\u2026", OrbMode.ORBITS),
    SEARCHING("Searching\u2026", OrbMode.GLOBE),
    SOLVING("Solving\u2026", OrbMode.RUBIK),
    LISTENING("Listening\u2026", OrbMode.WAVE),
    CONNECTING("Connecting\u2026", OrbMode.WEB),
    WEAVING("Weaving\u2026", OrbMode.BRAID),
    COMPOSING("Composing\u2026", OrbMode.RIBBON),
    BREATHING("Thinking\u2026", OrbMode.RING),
    SHAPING("Shaping\u2026", OrbMode.MORPH),
}

/** One distinct dot-geometry animation per state — shape + motion + density, never colour. */
enum class OrbMode { ORBITS, GLOBE, RUBIK, WAVE, WEB, BRAID, RIBBON, RING, MORPH }

/**
 * The two purpose-tuned sizes from the reference (separate designs, not a
 * scale factor): INLINE = message-status scale, STANDARD = assistant-avatar
 * scale. Each carries its own dot count, dot size and speed tuning.
 */
enum class OrbSize(val px: Int) { INLINE(20), STANDARD(64) }

/** Immutable resolved option set for the globe mode (upstream "fine" profile × preset multipliers). */
internal data class GlobeOpts(
    val latRings: Int,
    val lonDensity: Int,
    val rBase: Double,
    val rDepth: Double,
    val rBoost: Double,
    val inkFar: Double,
    val inkSpan: Double,
    val rsPow: Double,
    val rMin: Double,
    val scanMul: Double,
    val dimBase: Double,
)

/** Immutable resolved option set for the orbits mode (upstream "fine" profile × preset multipliers). */
internal data class OrbitsOpts(
    val orbitN: Int,
    val ghostN: Int,
    val ghostR: Double,
    val ghostA: Double,
    val particles: Int,
    val partR: Double,
    val partRDepth: Double,
    val rsPow: Double,
    val rMin: Double,
)

/** Immutable resolved option set for the rubik mode (upstream "fine" profile × preset multipliers). */
internal data class RubikOpts(
    val latRings: Int,
    val lonDensity: Int,
    val moveCount: Int,
    val rBase: Double,
    val rDepth: Double,
    val rActive: Double,
    val inkFar: Double,
    val inkSpan: Double,
    val rsPow: Double,
    val rMin: Double,
)

/** Immutable resolved option set for the wave mode (upstream "fine" profile × preset multipliers). */
internal data class WaveOpts(
    val rings: Int,
    val lonDensity: Int,
    val rBase: Double,
    val rDepth: Double,
    val rsPow: Double,
    val rMin: Double,
)

/** Immutable resolved option set for the web mode (upstream "fine" profile × preset multipliers). */
internal data class WebOpts(
    val nodeN: Int,
    val thr: Double,
    val signals: Int,
    val nodeR: Double,
    val nodeRDepth: Double,
    val lineW: Double,
    val rsPow: Double,
    val rMin: Double,
)

/** Immutable resolved option set for the braid mode (upstream "fine" profile × preset multipliers). */
internal data class BraidOpts(
    val strandN: Int,
    val turns: Double,
    val ghostN: Int,
    val rBase: Double,
    val rDepth: Double,
    val rsPow: Double,
    val rMin: Double,
)

/** Immutable resolved option set for the ribbon mode (upstream "fine" profile × preset multipliers). */
internal data class RibbonOpts(
    val lanes: Int,
    val segs: Int,
    val ghostN: Int,
    val spin: Double,
    val bandMul: Double,
    val wobMul: Double,
    val faceOn: Boolean,
    val rBase: Double,
    val rDepth: Double,
    val rsPow: Double,
    val rMin: Double,
)

/** Immutable resolved option set for the morph mode (upstream "fine" profile × preset multipliers). */
internal data class MorphOpts(
    val rDot: Double,
    val iconD: Double,
    val rMin: Double,
    val spread: Double,
)

/** A fully-resolved orb: which mode draws it, its clock speed, its exact options. */
internal data class ResolvedOrb(val mode: OrbMode, val speed: Double, val opts: Any)

internal object OrbSpec {
    /** Reduced-motion static representative frame (upstream paint contract). */
    const val STATIC_T = 0.6

    fun resolve(state: OrbState, size: OrbSize): ResolvedOrb = when (state) {
        OrbState.WORKING -> when (size) {
            OrbSize.STANDARD -> ResolvedOrb(OrbMode.ORBITS, 1.885, OrbitsOpts(orbitN = 12, ghostN = 40, ghostR = 0.9, ghostA = 0.5, particles = 3, partR = 1.2, partRDepth = 1.6, rsPow = 0.6, rMin = 0.3))
            OrbSize.INLINE -> ResolvedOrb(OrbMode.ORBITS, 3.9, OrbitsOpts(orbitN = 3, ghostN = 10, ghostR = 2.16, ghostA = 0.5, particles = 3, partR = 2.88, partRDepth = 3.84, rsPow = 0.6, rMin = 0.3))
        }
        OrbState.SEARCHING -> when (size) {
            OrbSize.STANDARD -> ResolvedOrb(OrbMode.GLOBE, 2.015, GlobeOpts(latRings = 11, lonDensity = 29, rBase = 0.69, rDepth = 1.9549999999999998, rBoost = 1.0, inkFar = 0.62, inkSpan = 0.54, rsPow = 0.6, rMin = 0.3, scanMul = 4.08, dimBase = 0.45))
            OrbSize.INLINE -> ResolvedOrb(OrbMode.GLOBE, 2.665, GlobeOpts(latRings = 6, lonDensity = 14, rBase = 1.05, rDepth = 2.975, rBoost = 1.0, inkFar = 0.62, inkSpan = 0.54, rsPow = 0.6, rMin = 0.3, scanMul = 4.335, dimBase = 0.45))
        }
        OrbState.SOLVING -> when (size) {
            OrbSize.STANDARD -> ResolvedOrb(OrbMode.RUBIK, 1.82, RubikOpts(latRings = 9, lonDensity = 24, moveCount = 14, rBase = 0.63, rDepth = 1.785, rActive = 0.315, inkFar = 0.62, inkSpan = 0.54, rsPow = 0.6, rMin = 0.3))
            OrbSize.INLINE -> ResolvedOrb(OrbMode.RUBIK, 1.95, RubikOpts(latRings = 4, lonDensity = 12, moveCount = 14, rBase = 1.14, rDepth = 3.23, rActive = 0.57, inkFar = 0.62, inkSpan = 0.54, rsPow = 0.6, rMin = 0.3))
        }
        OrbState.LISTENING -> when (size) {
            OrbSize.STANDARD -> ResolvedOrb(OrbMode.WAVE, 4.388, WaveOpts(rings = 9, lonDensity = 23, rBase = 0.6, rDepth = 1.7, rsPow = 0.6, rMin = 0.3))
            OrbSize.INLINE -> ResolvedOrb(OrbMode.WAVE, 3.998, WaveOpts(rings = 5, lonDensity = 13, rBase = 0.96, rDepth = 2.72, rsPow = 0.6, rMin = 0.3))
        }
        OrbState.CONNECTING -> when (size) {
            OrbSize.STANDARD -> ResolvedOrb(OrbMode.WEB, 3.315, WebOpts(nodeN = 41, thr = 0.72, signals = 7, nodeR = 1.3299999999999998, nodeRDepth = 1.71, lineW = 0.8, rsPow = 0.6, rMin = 0.3))
            OrbSize.INLINE -> ResolvedOrb(OrbMode.WEB, 6.63, WebOpts(nodeN = 8, thr = 0.72, signals = 1, nodeR = 2.1279999999999997, nodeRDepth = 2.736, lineW = 0.8, rsPow = 0.6, rMin = 0.3))
        }
        OrbState.WEAVING -> when (size) {
            OrbSize.STANDARD -> ResolvedOrb(OrbMode.BRAID, 1.625, BraidOpts(strandN = 26, turns = 3.0, ghostN = 75, rBase = 1.2, rDepth = 1.8, rsPow = 0.6, rMin = 0.3))
            OrbSize.INLINE -> ResolvedOrb(OrbMode.BRAID, 2.75, BraidOpts(strandN = 6, turns = 3.0, ghostN = 17, rBase = 1.6320000000000001, rDepth = 2.4480000000000004, rsPow = 0.6, rMin = 0.3))
        }
        OrbState.COMPOSING -> when (size) {
            OrbSize.STANDARD -> ResolvedOrb(OrbMode.RIBBON, 2.34, RibbonOpts(lanes = 3, segs = 44, ghostN = 38, spin = 0.0, bandMul = 3.9, wobMul = 1.0, faceOn = false, rBase = 0.935, rDepth = 1.4449999999999998, rsPow = 0.6, rMin = 0.3))
            OrbSize.INLINE -> ResolvedOrb(OrbMode.RIBBON, 3.12, RibbonOpts(lanes = 2, segs = 20, ghostN = 8, spin = 0.0, bandMul = 4.94, wobMul = 1.0, faceOn = false, rBase = 1.1803000000000001, rDepth = 1.8240999999999998, rsPow = 0.6, rMin = 0.3))
        }
        OrbState.BREATHING -> when (size) {
            OrbSize.STANDARD -> ResolvedOrb(OrbMode.RING, 3.24, RibbonOpts(lanes = 3, segs = 44, ghostN = 0, spin = 0.0, bandMul = 3.627, wobMul = 0.368, faceOn = true, rBase = 1.0516, rDepth = 1.6252, rsPow = 0.6, rMin = 0.3))
            OrbSize.INLINE -> ResolvedOrb(OrbMode.RING, 3.78, RibbonOpts(lanes = 2, segs = 15, ghostN = 0, spin = 0.0, bandMul = 3.968, wobMul = 0.565, faceOn = true, rBase = 1.7842000000000002, rDepth = 2.7574, rsPow = 0.6, rMin = 0.3))
        }
        OrbState.SHAPING -> when (size) {
            OrbSize.STANDARD -> ResolvedOrb(OrbMode.MORPH, 2.405, MorphOpts(rDot = 0.008295, iconD = 0.702, rMin = 0.25, spread = 1.45))
            OrbSize.INLINE -> ResolvedOrb(OrbMode.MORPH, 2.08, MorphOpts(rDot = 0.021231, iconD = 0.53, rMin = 0.25, spread = 1.45))
        }
    }
}
