// GENERATED by scripts/gen-orb-spec.mjs from docs/orbs/orbs-spec.json (thinking-orbs@0.3.1, specVersion 1.0.0). DO NOT hand-edit — regenerate.
import Foundation

/// The nine activity states an AI assistant can be in — the logical model the
/// product maps its REAL application states onto (never the reverse; see the
/// mapping helpers in ThinkingOrbView.swift).
public enum OrbState: String, CaseIterable, Sendable {
    case working, searching, solving, listening, connecting, weaving, composing, breathing, shaping

    /// Human-readable per-state label (also the accessibility description).
    public var label: String {
        switch self {
        case .working: return "Working…"
        case .searching: return "Searching…"
        case .solving: return "Solving…"
        case .listening: return "Listening…"
        case .connecting: return "Connecting…"
        case .weaving: return "Weaving…"
        case .composing: return "Composing…"
        case .breathing: return "Thinking…"
        case .shaping: return "Shaping…"
        }
    }

    /// The distinct dot-geometry animation behind this state.
    public var mode: OrbMode {
        switch self {
        case .working: return .orbits
        case .searching: return .globe
        case .solving: return .rubik
        case .listening: return .wave
        case .connecting: return .web
        case .weaving: return .braid
        case .composing: return .ribbon
        case .breathing: return .ring
        case .shaping: return .morph
        }
    }
}

/// One distinct dot-geometry animation per state — shape + motion + density, never colour.
public enum OrbMode: Sendable {
    case orbits, globe, rubik, wave, web, braid, ribbon, ring, morph
}

/// The two purpose-tuned sizes from the reference (separate designs, not a
/// scale factor): inline = message-status scale, standard = assistant-avatar scale.
public enum OrbSize: Int, Sendable {
    case inline = 20
    case standard = 64
}

/// Immutable resolved option set for the globe mode (upstream "fine" profile × preset multipliers).
public struct GlobeOpts {
    let latRings: Int
    let lonDensity: Int
    let rBase: Double
    let rDepth: Double
    let rBoost: Double
    let inkFar: Double
    let inkSpan: Double
    let rsPow: Double
    let rMin: Double
    let scanMul: Double
    let dimBase: Double
    public init(latRings: Int, lonDensity: Int, rBase: Double, rDepth: Double, rBoost: Double, inkFar: Double, inkSpan: Double, rsPow: Double, rMin: Double, scanMul: Double, dimBase: Double) {
        self.latRings = latRings
        self.lonDensity = lonDensity
        self.rBase = rBase
        self.rDepth = rDepth
        self.rBoost = rBoost
        self.inkFar = inkFar
        self.inkSpan = inkSpan
        self.rsPow = rsPow
        self.rMin = rMin
        self.scanMul = scanMul
        self.dimBase = dimBase
    }
}

/// Immutable resolved option set for the orbits mode (upstream "fine" profile × preset multipliers).
public struct OrbitsOpts {
    let orbitN: Int
    let ghostN: Int
    let ghostR: Double
    let ghostA: Double
    let particles: Int
    let partR: Double
    let partRDepth: Double
    let rsPow: Double
    let rMin: Double
    public init(orbitN: Int, ghostN: Int, ghostR: Double, ghostA: Double, particles: Int, partR: Double, partRDepth: Double, rsPow: Double, rMin: Double) {
        self.orbitN = orbitN
        self.ghostN = ghostN
        self.ghostR = ghostR
        self.ghostA = ghostA
        self.particles = particles
        self.partR = partR
        self.partRDepth = partRDepth
        self.rsPow = rsPow
        self.rMin = rMin
    }
}

/// Immutable resolved option set for the rubik mode (upstream "fine" profile × preset multipliers).
public struct RubikOpts {
    let latRings: Int
    let lonDensity: Int
    let moveCount: Int
    let rBase: Double
    let rDepth: Double
    let rActive: Double
    let inkFar: Double
    let inkSpan: Double
    let rsPow: Double
    let rMin: Double
    public init(latRings: Int, lonDensity: Int, moveCount: Int, rBase: Double, rDepth: Double, rActive: Double, inkFar: Double, inkSpan: Double, rsPow: Double, rMin: Double) {
        self.latRings = latRings
        self.lonDensity = lonDensity
        self.moveCount = moveCount
        self.rBase = rBase
        self.rDepth = rDepth
        self.rActive = rActive
        self.inkFar = inkFar
        self.inkSpan = inkSpan
        self.rsPow = rsPow
        self.rMin = rMin
    }
}

/// Immutable resolved option set for the wave mode (upstream "fine" profile × preset multipliers).
public struct WaveOpts {
    let rings: Int
    let lonDensity: Int
    let rBase: Double
    let rDepth: Double
    let rsPow: Double
    let rMin: Double
    public init(rings: Int, lonDensity: Int, rBase: Double, rDepth: Double, rsPow: Double, rMin: Double) {
        self.rings = rings
        self.lonDensity = lonDensity
        self.rBase = rBase
        self.rDepth = rDepth
        self.rsPow = rsPow
        self.rMin = rMin
    }
}

/// Immutable resolved option set for the web mode (upstream "fine" profile × preset multipliers).
public struct WebOpts {
    let nodeN: Int
    let thr: Double
    let signals: Int
    let nodeR: Double
    let nodeRDepth: Double
    let lineW: Double
    let rsPow: Double
    let rMin: Double
    public init(nodeN: Int, thr: Double, signals: Int, nodeR: Double, nodeRDepth: Double, lineW: Double, rsPow: Double, rMin: Double) {
        self.nodeN = nodeN
        self.thr = thr
        self.signals = signals
        self.nodeR = nodeR
        self.nodeRDepth = nodeRDepth
        self.lineW = lineW
        self.rsPow = rsPow
        self.rMin = rMin
    }
}

/// Immutable resolved option set for the braid mode (upstream "fine" profile × preset multipliers).
public struct BraidOpts {
    let strandN: Int
    let turns: Double
    let ghostN: Int
    let rBase: Double
    let rDepth: Double
    let rsPow: Double
    let rMin: Double
    public init(strandN: Int, turns: Double, ghostN: Int, rBase: Double, rDepth: Double, rsPow: Double, rMin: Double) {
        self.strandN = strandN
        self.turns = turns
        self.ghostN = ghostN
        self.rBase = rBase
        self.rDepth = rDepth
        self.rsPow = rsPow
        self.rMin = rMin
    }
}

/// Immutable resolved option set for the ribbon mode (upstream "fine" profile × preset multipliers).
public struct RibbonOpts {
    let lanes: Int
    let segs: Int
    let ghostN: Int
    let spin: Double
    let bandMul: Double
    let wobMul: Double
    let faceOn: Bool
    let rBase: Double
    let rDepth: Double
    let rsPow: Double
    let rMin: Double
    public init(lanes: Int, segs: Int, ghostN: Int, spin: Double, bandMul: Double, wobMul: Double, faceOn: Bool, rBase: Double, rDepth: Double, rsPow: Double, rMin: Double) {
        self.lanes = lanes
        self.segs = segs
        self.ghostN = ghostN
        self.spin = spin
        self.bandMul = bandMul
        self.wobMul = wobMul
        self.faceOn = faceOn
        self.rBase = rBase
        self.rDepth = rDepth
        self.rsPow = rsPow
        self.rMin = rMin
    }
}

/// Immutable resolved option set for the morph mode (upstream "fine" profile × preset multipliers).
public struct MorphOpts {
    let rDot: Double
    let iconD: Double
    let rMin: Double
    let spread: Double
    public init(rDot: Double, iconD: Double, rMin: Double, spread: Double) {
        self.rDot = rDot
        self.iconD = iconD
        self.rMin = rMin
        self.spread = spread
    }
}

/// A fully-resolved orb: which mode draws it, its clock speed, its exact options.
public struct ResolvedOrb: Sendable {
    public let mode: OrbMode
    public let speed: Double
    public let opts: OrbOpts
}

public enum OrbOpts: Sendable {
    case orbits(OrbitsOpts)
    case globe(GlobeOpts)
    case rubik(RubikOpts)
    case wave(WaveOpts)
    case web(WebOpts)
    case braid(BraidOpts)
    case ribbon(RibbonOpts)
    case ring(RibbonOpts)
    case morph(MorphOpts)
}

public enum OrbSpec {
    /// Reduced-motion static representative frame (upstream paint contract).
    public static let staticT = 0.6

    public static func resolve(state: OrbState, size: OrbSize) -> ResolvedOrb {
        switch state {
        case .working:
            switch size {
            case .standard: return ResolvedOrb(mode: .orbits, speed: 1.885, opts: .orbits(OrbitsOpts(orbitN = 12, ghostN = 40, ghostR = 0.9, ghostA = 0.5, particles = 3, partR = 1.2, partRDepth = 1.6, rsPow = 0.6, rMin = 0.3)))
            case .inline: return ResolvedOrb(mode: .orbits, speed: 3.9, opts: .orbits(OrbitsOpts(orbitN = 3, ghostN = 10, ghostR = 2.16, ghostA = 0.5, particles = 3, partR = 2.88, partRDepth = 3.84, rsPow = 0.6, rMin = 0.3)))
            }
        case .searching:
            switch size {
            case .standard: return ResolvedOrb(mode: .globe, speed: 2.015, opts: .globe(GlobeOpts(latRings = 11, lonDensity = 29, rBase = 0.69, rDepth = 1.9549999999999998, rBoost = 1.0, inkFar = 0.62, inkSpan = 0.54, rsPow = 0.6, rMin = 0.3, scanMul = 4.08, dimBase = 0.45)))
            case .inline: return ResolvedOrb(mode: .globe, speed: 2.665, opts: .globe(GlobeOpts(latRings = 6, lonDensity = 14, rBase = 1.05, rDepth = 2.975, rBoost = 1.0, inkFar = 0.62, inkSpan = 0.54, rsPow = 0.6, rMin = 0.3, scanMul = 4.335, dimBase = 0.45)))
            }
        case .solving:
            switch size {
            case .standard: return ResolvedOrb(mode: .rubik, speed: 1.82, opts: .rubik(RubikOpts(latRings = 9, lonDensity = 24, moveCount = 14, rBase = 0.63, rDepth = 1.785, rActive = 0.315, inkFar = 0.62, inkSpan = 0.54, rsPow = 0.6, rMin = 0.3)))
            case .inline: return ResolvedOrb(mode: .rubik, speed: 1.95, opts: .rubik(RubikOpts(latRings = 4, lonDensity = 12, moveCount = 14, rBase = 1.14, rDepth = 3.23, rActive = 0.57, inkFar = 0.62, inkSpan = 0.54, rsPow = 0.6, rMin = 0.3)))
            }
        case .listening:
            switch size {
            case .standard: return ResolvedOrb(mode: .wave, speed: 4.388, opts: .wave(WaveOpts(rings = 9, lonDensity = 23, rBase = 0.6, rDepth = 1.7, rsPow = 0.6, rMin = 0.3)))
            case .inline: return ResolvedOrb(mode: .wave, speed: 3.998, opts: .wave(WaveOpts(rings = 5, lonDensity = 13, rBase = 0.96, rDepth = 2.72, rsPow = 0.6, rMin = 0.3)))
            }
        case .connecting:
            switch size {
            case .standard: return ResolvedOrb(mode: .web, speed: 3.315, opts: .web(WebOpts(nodeN = 41, thr = 0.72, signals = 7, nodeR = 1.3299999999999998, nodeRDepth = 1.71, lineW = 0.8, rsPow = 0.6, rMin = 0.3)))
            case .inline: return ResolvedOrb(mode: .web, speed: 6.63, opts: .web(WebOpts(nodeN = 8, thr = 0.72, signals = 1, nodeR = 2.1279999999999997, nodeRDepth = 2.736, lineW = 0.8, rsPow = 0.6, rMin = 0.3)))
            }
        case .weaving:
            switch size {
            case .standard: return ResolvedOrb(mode: .braid, speed: 1.625, opts: .braid(BraidOpts(strandN = 26, turns = 3.0, ghostN = 75, rBase = 1.2, rDepth = 1.8, rsPow = 0.6, rMin = 0.3)))
            case .inline: return ResolvedOrb(mode: .braid, speed: 2.75, opts: .braid(BraidOpts(strandN = 6, turns = 3.0, ghostN = 17, rBase = 1.6320000000000001, rDepth = 2.4480000000000004, rsPow = 0.6, rMin = 0.3)))
            }
        case .composing:
            switch size {
            case .standard: return ResolvedOrb(mode: .ribbon, speed: 2.34, opts: .ribbon(RibbonOpts(lanes = 3, segs = 44, ghostN = 38, spin = 0.0, bandMul = 3.9, wobMul = 1.0, faceOn = false, rBase = 0.935, rDepth = 1.4449999999999998, rsPow = 0.6, rMin = 0.3)))
            case .inline: return ResolvedOrb(mode: .ribbon, speed: 3.12, opts: .ribbon(RibbonOpts(lanes = 2, segs = 20, ghostN = 8, spin = 0.0, bandMul = 4.94, wobMul = 1.0, faceOn = false, rBase = 1.1803000000000001, rDepth = 1.8240999999999998, rsPow = 0.6, rMin = 0.3)))
            }
        case .breathing:
            switch size {
            case .standard: return ResolvedOrb(mode: .ring, speed: 3.24, opts: .ribbon(RibbonOpts(lanes = 3, segs = 44, ghostN = 0, spin = 0.0, bandMul = 3.627, wobMul = 0.368, faceOn = true, rBase = 1.0516, rDepth = 1.6252, rsPow = 0.6, rMin = 0.3)))
            case .inline: return ResolvedOrb(mode: .ring, speed: 3.78, opts: .ribbon(RibbonOpts(lanes = 2, segs = 15, ghostN = 0, spin = 0.0, bandMul = 3.968, wobMul = 0.565, faceOn = true, rBase = 1.7842000000000002, rDepth = 2.7574, rsPow = 0.6, rMin = 0.3)))
            }
        case .shaping:
            switch size {
            case .standard: return ResolvedOrb(mode: .morph, speed: 2.405, opts: .morph(MorphOpts(rDot = 0.008295, iconD = 0.702, rMin = 0.25, spread = 1.45)))
            case .inline: return ResolvedOrb(mode: .morph, speed: 2.08, opts: .morph(MorphOpts(rDot = 0.021231, iconD = 0.53, rMin = 0.25, spread = 1.45)))
            }
        }
    }
}
